articles/urls.py
from django.conf.urls.defaults import *

from articles import views
from articles.feeds import TagFeed, LatestEntries, TagFeedAtom, LatestEntriesAtom

tag_rss = TagFeed()
latest_rss = LatestEntries()
tag_atom = TagFeedAtom()
latest_atom = LatestEntriesAtom()

urlpatterns = patterns('',
    (r'^(?P<year>\d{4})/(?P<month>.{3})/(?P<day>\d{1,2})/(?P<slug>.*)/$', views.redirect_to_article),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/page/(?P<page>\d+)/$', views.display_blog_page, name='articles_in_month_page'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', views.display_blog_page, name='articles_in_month'),
)

urlpatterns += patterns('',
    url(r'^$', views.display_blog_page, name='articles_archive'),
    url(r'^page/(?P<page>\d+)/$', views.display_blog_page, name='articles_archive_page'),

    url(r'^tag/(?P<tag>.*)/page/(?P<page>\d+)/$', views.display_blog_page, name='articles_display_tag_page'),
    url(r'^tag/(?P<tag>.*)/$', views.display_blog_page, name='articles_display_tag'),

    url(r'^author/(?P<username>.*)/page/(?P<page>\d+)/$', views.display_blog_page, name='articles_by_author_page'),
    url(r'^author/(?P<username>.*)/$', views.display_blog_page, name='articles_by_author'),

    url(r'^(?P<year>\d{4})/(?P<slug>.*)/$', views.display_article, name='articles_display_article'),

    # AJAX
    url(r'^ajax/tag/autocomplete/$', views.ajax_tag_autocomplete, name='articles_tag_autocomplete'),

    # RSS
    url(r'^feeds/latest\.rss$', latest_rss, name='articles_rss_feed_latest'),
    url(r'^feeds/latest/$', latest_rss),
    url(r'^feeds/tag/(?P<slug>[\w_-]+)\.rss$', tag_rss, name='articles_rss_feed_tag'),
    url(r'^feeds/tag/(?P<slug>[\w_-]+)/$', tag_rss),

    # Atom
    url(r'^feeds/atom/latest\.xml$', latest_atom, name='articles_atom_feed_latest'),
    url(r'^feeds/atom/tag/(?P<slug>[\w_-]+)\.xml$', tag_atom, name='articles_atom_feed_tag'),

)

danhawkes/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from danhawkes import settings, views
from django.views.generic.simple import direct_to_template


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.index, name='danhawkes-home'),
    url(r'^portfolio/', include('portfolio.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('articles.urls')),
    url(r'^cv/', views.cv, name='danhawkes-cv'),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', \
        {'template_name': 'danhawkes/login.html'}, name='danhawkes-login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', \
        {'template_name': 'danhawkes/logout.html'}, name='danhawkes-logout'),
    url(r'^accounts/profile/$', direct_to_template, \
        {'template': 'danhawkes/profile.html'}, name='danhawkes-profile'),
    url(r'^robots.txt$', direct_to_template, \
        {'template': 'danhawkes/robots.txt', 'mimetype': 'text/plain'}),
    url(r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', \
        {'url': settings.STATIC_URL + 'danhawkes/img/favicon.ico'}),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),)

urlpatterns += staticfiles_urlpatterns()

portfolio/urls.py
from django.conf.urls import patterns, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from portfolio import views


urlpatterns = patterns('',
    url(r'^$', views.index, name='portfolio-index'),
    url(r'^processingjs/tentacles/$', views.tentacles, name='tentacles'),
    url(r'^(?P<project_id>\S+)/$', views.detail, name='portfolio-detail'),
)

urlpatterns += staticfiles_urlpatterns()

portfolio/models.py
from django.db import models
from datetime import datetime
import markdown
from articles.utils import ReadOnlyCachedAttribute


class Project(models.Model):
    _MARKUP_NONE = 'none'
    _MARKUP_MARKDOWN = 'markdown'
    _MARKUP_CHOICES = ((_MARKUP_NONE, 'None'), (_MARKUP_MARKDOWN, 'Markdown'))
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    summary = models.CharField(max_length=200, blank=True, help_text='A one-line summary of the project.')
    description = models.TextField(max_length=2000, blank=True)
    markup = models.CharField(max_length=20, choices=_MARKUP_CHOICES, default=_MARKUP_MARKDOWN, help_text='The markup language used in the description text.')
    icon = models.ImageField(blank=True, upload_to='img');
    date_published = models.DateField(verbose_name='publication date', default=datetime.now)
    licence = models.ForeignKey('Licence', null=True, blank=True)
    client = models.ForeignKey('Client')
    tags = models.ManyToManyField('Tag', null=True)
    rank = models.PositiveSmallIntegerField()
    
    
    def __init__(self, *args, **kwargs):
        models.Model.__init__(self, *args, **kwargs)
        self._rendered_description = markdown.markdown(self.description)

    def __unicode__(self):
        return self.name

    @ReadOnlyCachedAttribute
    def rendered_description(self):
        if self.markup == Project._MARKUP_MARKDOWN:
            return markdown.markdown(self.description)
        else:
            return self.description
        
    def links(self):
        links = []
        links.extend(self.filelink_set.all())
        links.extend(self.externallink_set.all())
        return links
    
    class Meta:
        ordering = ('rank',)
    
class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __unicode__(self):
        return self.name
    
    class Meta:
        ordering = ('name',)
    
class Client(models.Model):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name

class Licence(models.Model):
    LICENCE_CHOICES = (('freebsd', 'FreeBSD'), ('apache', 'Apache'), ('gpl', 'GPL'), ('proprietary', 'Proprietary'))
    name = models.CharField(max_length=50, choices=LICENCE_CHOICES)
    version = models.CharField(max_length=20, blank=True)

    def __unicode__(self):
        return self.name + ' ' + self.version

class Link(models.Model):
    project = models.ForeignKey('Project')
    annotation = models.CharField(max_length=200, blank=True)
    target_blank = models.BooleanField(default=False, help_text='Forces the link to open in a new tab/window.')

    class Meta:
        abstract = True

class FileLink(Link):
    upload_to = lambda inst, filename: 'portfolio/%s/files/%s' % (inst.project.slug, filename)
    file = models.FileField(upload_to=upload_to)

class ExternalLink(Link):
    url = models.URLField()

class Image(models.Model):
    project = models.ForeignKey('Project')
    upload_to = lambda inst, filename: 'portfolio/%s/img/%s' % (inst.project.slug, filename)
    file = models.ImageField(upload_to=upload_to, width_field='width', height_field='height')
    caption = models.CharField(max_length=200, blank=True)
    width = models.PositiveIntegerField(editable=False)
    height = models.PositiveIntegerField(editable=False)

portfolio/views.py
from django.shortcuts import render_to_response
from portfolio.models import Project, Tag, Client
from django.template.context import RequestContext
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    project_list = Project.objects.all().order_by('rank')
    param_dict = {'page_title':'Portfolio', 'project_list':project_list}
    return render_to_response('portfolio/index.html', param_dict, RequestContext(request))

@login_required
def detail(request, project_id):
    try:
        project = Project.objects.get(pk=int(project_id, 10))
    except ObjectDoesNotExist:
        raise Http404
    except ValueError:
        try:
            project = Project.objects.get(slug__iexact=project_id)
        except ObjectDoesNotExist:
            raise Http404
    
    if request.GET.get('embedded', False) == 'true':
        template = 'portfolio/embedded.html'
        param_dict = {'page_title':'Portfolio', 'project':project, 'title':'Portfolio', 'subtitle':project.name}
    else:
        template = 'portfolio/detail.html'
        param_dict = {'page_title':'Portfolio', 'project':project, 'title':'Portfolio', 'subtitle':project.name}
    
    return render_to_response(template, param_dict, RequestContext(request))

@login_required
def tentacles(request):
    return render_to_response('portfolio/processing/tentacles.html')
    

portfolio/templates/portfolio/detail.html
{% extends 'danhawkes/base-site.html' %}
{% load project_helpers %}

{% block head %}
	{{ block.super }}
	{% include 'portfolio/components/head.html' %}
{% endblock %}

{% block title %}
	Portfolio
{% endblock %}

{% block subtitle %}
	{{project.name}}
{% endblock %}

{% block content %}
	{{ block.super }}
	<div class="row">
		<div class="eight columns">
				{{ project.rendered_description|safe }}
		        {% render_tags project.tags.all %}
		        {% render_link_list project.links %} 
		</div>
		<div class="four columns">
			{% render_orbit_image_viewer project.image_set.all tag_id='detailimages' %}
		</div>
	</div>
{% endblock %} 

{% block aftercontent %}
	{{ block.super }}

	<script type="text/javascript">
	$('#detailimages').orbit({
		advanceSpeed : 4000,
		captions : true,
		pauseOnHover : true,
		startClockOnMouseOut : true,
		startClockOnMouseOutAfter : 0,
		timer:true,
		animation:'fade'
	});
	</script>
{% endblock %}

portfolio/templates/portfolio/embedded.html
{% load humanize %}
{% load project_helpers %}

	<div class="row">
		<div class="twelve columns">
			<h3>{{project.name}} <small>{{ project.date_published|date:"F, Y" }}</small></h3><hr/>
		</div>
	</div>

	<div class="row">
		<div class="eight columns">
		    {% render_link_list project.links %} 
			{{ project.rendered_description|safe }}
			{{ project.client }}
		</div>
	</div>

portfolio/templates/portfolio/index.html
{% extends 'danhawkes/base-site.html' %} {% load humanize %} {% load project_helpers %} 

{% block head %} {{ block.super }}
<link rel="stylesheet" href="{{STATIC_URL}}portfolio/css/index.css">
{% endblock %}

{% block title %}Portfolio{% endblock %}

{% block content %}
<div class="row project-row">
	<div class="twelve columns">
		<h6 class="subheader">You may also be interested in my<a href="{% url danhawkes-cv %}"> CV.&nbsp;&nbsp;&rarr;&nbsp;&nbsp;&nbsp;&nbsp;</a></h4>
		<hr/>
	</div>
</div>

{% for project in project_list %}
<div class="row project-row">
	<div class="twelve columns">
		<div class="row">
			<div class="eight columns {% cycle '' 'push-four' %}">
				<a name="{{ project.slug }}"></a>
				<h4>
					<a name="" class="project-link" data-url="{% url portfolio.views.detail project.slug %}">{{ project.name }} 
					{% if project.client.name != 'None' %}<small>{{ project.client.name }}</small>{% endif %}</a>
				</h4>
				<div class="project-description">{{ project.rendered_description|safe }}</div>
				{% if project.links %}
					<h5 class="subheader">Links</h5>
					{% render_link_list project.links %}
				{% endif %}
				<h5 class="subheader">Tags</h5>
				{% render_tags project.tags.all %}
			</div>
			<div class="four columns {% cycle '' 'pull-eight' %}">
				{% render_orbit_image_viewer project.image_set.all tag_class='indeximages' %}
			</div>
		</div>
		{%if not forloop.last %}<hr />{% endif %}
	</div>
</div>
{% endfor %}
{% endblock content %} 

{% block aftercontent %} {{ block.super }}

<script type="text/javascript">
	
	if (window.innerWidth > 1300) {
		$('body').append('<div id="mymodal" class="reveal-modal medium"><a class="close-reveal-modal">&#215;</a><div id="mymodalcontent"></div></div>');
	} else if (window.innerWidth > 600) {
		$('body').append('<div id="mymodal" class="reveal-modal large"><a class="close-reveal-modal">&#215;</a><div id="mymodalcontent"></div></div>');
	}	
	
	$('.project-link').click(function(event) {
		/* url = $(this).attr('data-url');
		if ($('#mymodal').length) {
			$('#mymodal').reveal({
				animation:'fade',
				open:function(){
					$('#mymodalcontent').load(url+'?embedded=true');
				}
			});
		} else {
			window.location.href = url;
		}
		 event.preventDefault(); */
	});
	
	$('.indeximages').orbit({
		advanceSpeed : 4000,
		captions : true,
		pauseOnHover : true,
		startClockOnMouseOut : true,
		startClockOnMouseOutAfter : 0,
		timer:true,
		animation:'fade'
	});

</script>

{% endblock aftercontent %}